---
# tasks file for prometheus

- name: prometheus | ensure variables are defined for smtp
  assert:
    that:
      - lookup('vars', item) | length > 0
    fail_msg: Required variable {{ item }} is not well defined
    success_msg: Required variable {{ item }} is well defined
  loop:
    - prometheus_alertmanager_smtp_smarthost
    - prometheus_alertmanager_smtp_to
    - prometheus_alertmanager_smtp_from
  when: prometheus_alertmanager_enabled and prometheus_alertmanager_smtp_enable

- name: prometheus | ensure there is a port in the smarthost
  assert:
    that:
      - prometheus_alertmanager_smtp_smarthost is match('.*:\d{2,}$')
    fail_msg: Port is missing from prometheus_alertmanager_smtp_smarthost
  when: prometheus_alertmanager_enabled and prometheus_alertmanager_smtp_enable

- name: prometheus | ensure variables are defined for authenticated smtp
  assert:
    that:
      - lookup('vars', item) | length > 0
    fail_msg: Required variable {{ item }} is not well defined
    success_msg: Required variable {{ item }} is well defined
  loop:
    - prometheus_alertmanager_smtp_username
    - prometheus_alertmanager_smtp_password
  when: prometheus_alertmanager_smtp_username is not none and prometheus_alertmanager_smtp_username | length > 0

- name: prometheus | create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/targets
    - /etc/prometheus/targets/manual
    - /etc/prometheus/templates

- name: prometheus | prometheus configuration file
  become: true
  template:
    dest: /etc/prometheus/prometheus.yml
    force: true
    src: etc-prometheus-prometheus-yml.j2
    mode: 0644
  register: prometheus_configuration
  when: prometheus_configuration_static is false and prometheus_configuration_static_file | length == 0

- name: Debug template result
  debug:
    msg:
      - "Task skipped: {{ prometheus_configuration.skipped | default(false) }}"
      - "Changed: {{ prometheus_configuration.changed | default('UNDEFINED') }}"
      - "Full result: {{ prometheus_configuration }}"

- name: prometheus | prometheus static configuration file
  become: true
  template:
    dest: /etc/prometheus/prometheus.yml
    force: true
    src: "{{ prometheus_configuration_static_file }}"
    mode: 0644
  register: prometheus_configuration_static_file_var
  when: prometheus_configuration_static_file | length > 0

- name: prometheus | web configuration file
  become: true
  template:
    dest: /etc/prometheus/web.yml
    force: true
    src: etc-prometheus-web-yml.j2
    mode: 0644
  register: prometheus_web_configuration
  when: prometheus_web_configuration_static is false and prometheus_web_configuration_static_file | length == 0

- name: prometheus | prometheus web static configuration file
  become: true
  template:
    dest: /etc/prometheus/web.yml
    force: true
    src: "{{ prometheus_web_configuration_static_file }}"
    mode: 0644
  register: prometheus_web_configuration
  when: prometheus_web_configuration_static_file | length > 0

- name: prometheus | prometheus alert rules
  become: true
  template:
    dest: /etc/prometheus/rules/default-alert.rules.yml
    force: true
    src: etc-prometheus-default-alert-rules-yml.j2
    mode: 0644
  register: prometheus_alert_rules

- name: prometheus | validate rule file names
  assert:
    that:
      - item is match('.*\\.rules\\.yml$')
    fail_msg: "File {{ item }} does not match pattern *.rules.yml"
  loop: "{{ prometheus_additional_rules_files }}"
  when: prometheus_additional_rules_files is defined and prometheus_additional_rules_files | length > 0

- name: prometheus | additional alert rule files
  become: true
  copy:
    dest: /etc/prometheus/rules/
    src: "{{ item }}"
    mode: '0644'
  loop: "{{ prometheus_additional_rules_files }}"
  when: prometheus_additional_rules_files is defined
  register: prometheus_alert_rules_additional

- name: prometheus | prometheus additional alert rules
  become: true
  template:
    dest: /etc/prometheus/rules/additional-alert.rules.yml
    force: true
    src: "{{ prometheus_additional_rules_template }}"
    mode: 0644
  register: prometheus_alert_rules_additional_2

- name: prometheus | blackbox configuration file
  become: true
  template:
    dest: /etc/prometheus/blackbox-exporter.yml
    force: true
    src: etc-prometheus-blackbox-exporter.yml.j2
    mode: 0644
  register: prometheus_blackboxexporter_configuration
  when: prometheus_blackboxexporter_configuration_static is false and prometheus_blackboxexporter_configuration_static_file | length == 0

- name: prometheus | prometheus backbox static configuration file
  become: true
  template:
    dest: /etc/prometheus/blackbox-exporter.yml
    force: true
    src: "{{ prometheus_blackboxexporter_configuration_static_file }}"
    mode: 0644
  register: prometheus_blackboxexporter_configuration
  when: prometheus_blackboxexporter_configuration_static_file | length > 0

- name: prometheus | file sd configs
  become: true
  template:
    dest: /etc/prometheus/targets/{{ item.groupname }}.yml
    force: true
    src: file_sd_config-template-yml.j2
    mode: 0644
  with_items:
    - "{{ prometheus_sd_targets }}"

# Docker containers

- name: prometheus | docker-python
  become: true
  apt:
    name: python3-docker
    state: present

- name: prometheus | docker started
  become: true
  service:
    name: docker
    state: started

- name: prometheus | docker network
  become: true
  docker_network:
    name: "{{ prometheus_docker_network }}"
    state: present

- name: prometheus | docker nextcloud exporter
  become: true
  docker_container:
    command: >
      --server "{{ item.host }}"
      --auth-token "{{ item.auth_token }}"
      --addr ":{{ item.port }}"
    image: ghcr.io/xperimental/nextcloud-exporter:{{ prometheus_nextcloudexporter_version }}
    name: "nextcloud-exporter-{{ item.identifier }}"
    networks:
      - name: "{{ prometheus_docker_network }}"
    published_ports: "{{ prometheus_nextcloudexporter_listen_ip }}:{{ item.port }}:{{ item.port }}"
    restart_policy: always
    state: started
  with_items:
     "{{ prometheus_nextcloud_targets }}"

- name: prometheus | docker opnsense exporter
  become: true
  docker_container:
    command: >
      --log.level=info
      --opnsense.address="{{ item.host }}"
      --opnsense.api-key="{{ item.api_key }}"
      --opnsense.api-secret="{{ item.api_secret }}"
      --exporter.instance-label="{{ item.label }}"
      --web.listen-address=:"{{ item.port }}"
      --opnsense.protocol="{{ item.protocol }}"
      --opnsense.insecure
    image: ghcr.io/athennamind/opnsense-exporter:{{ prometheus_opnsenseexporter_version }}
    name: "opnsense-exporter-{{ item.identifier }}"
    networks:
      - name: "{{ prometheus_docker_network }}"
    published_ports: "{{ item.listen_address }}:{{ item.port }}:{{ item.port }}"
    restart_policy: always
    state: started
  with_items:
     "{{ prometheus_opnsense_targets }}"

- name: prometheus | docker blackbox-exporter
  become: true
  docker_container:
    command: >
      --config.file=/etc/prometheus/blackbox-exporter.yml
      {{ prometheus_blackboxexporter_additional_command_args }}
    image: prom/blackbox-exporter:v{{ prometheus_blackboxexporter_version }}
    name: blackbox-exporter
    networks:
      - name: "{{ prometheus_docker_network }}"
    published_ports: "{{ prometheus_blackboxexporter_listen_ip }}:{{prometheus_blackboxexporter_port}}:{{prometheus_blackboxexporter_port}}"
    # read_only: True
    recreate: "{{ prometheus_blackboxexporter_configuration.changed }}"
    restart_policy: always
    state: started
    volumes:
      - /etc/prometheus/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml:ro
  register: _blackboxexporter_container

- name: prometheus | docker prometheus
  become: true
  docker_container:
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.config.file=/etc/prometheus/web.yml
      {{ '--web.enable-remote-write-receiver' if prometheus_remote_write_enabled | default(false) else '' }}
      {{ prometheus_additional_command_args }}
    image: prom/prometheus:v{{ prometheus_version }}
    name: prometheus
    networks:
      - name: "{{ prometheus_docker_network }}"
    published_ports: "{{ prometheus_listen_ip }}:{{ prometheus_port }}:{{ prometheus_port }}"
    # read_only: True
    recreate: >-
      {{ prometheus_configuration.changed or
         prometheus_configuration_static_file_var.changed or
         prometheus_web_configuration.changed or
         prometheus_alert_rules.changed or
         prometheus_alert_rules_additional.changed or
         prometheus_alert_rules_additional2.changed }}
    restart_policy: always
    state: started
    user: "{{ prometheus_docker_user | default(omit) }}"
    volumes:
      # We could mount /etc/prometheus instead but the Docker image contains
      # additional (optional) files
      - /etc/prometheus/rules/:/etc/prometheus/rules/:ro
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/prometheus/web.yml:/etc/prometheus/web.yml:ro
      - /etc/prometheus/targets/:/etc/prometheus/targets/:ro
      - "{{ prometheus_docker_data_volume }}:/prometheus"
  register: _prometheus_container

- name: prometheus | alertmanager
  include_tasks: alertmanager.yml
  when: prometheus_alertmanager_enabled is true

- name: prometheus | sachet
  include_tasks: sachet.yml
  when: prometheus_sachet_enable is true

# In certain situations if a manual change means Prometheus in Docker
# auto restarted but a host mounted file wasn't present it'll be auto
# created as a directory instead of a file.
- name: prometheus | check docker host file mounts
  stat:
    path: "{{ item }}"
  with_items:
    - /etc/prometheus/alertmanager.yml
    - /etc/prometheus/blackbox-exporter.yml
    - /etc/prometheus/prometheus.yml
  register: prometheus_docker_file_mounts

- name: prometheus | assert docker host file mounts
  assert:
    that: 'item.stat.isreg'
  with_items: "{{ prometheus_docker_file_mounts.results }}"
  # This is a sanity check so use no_log to reduce the excessive log output
  # (there's nothing senstive in there)
  # The asserts will be in the same order as the previous task
  no_log: true

- name: prometheus | lookup prometheus container IP
  command:  docker inspect --format '{''{ .NetworkSettings.Networks.{{ prometheus_docker_network }}.IPAddress}''}' prometheus
  register: _prometheus_container_ip

- name: prometheus | lookup blackboxexporter container IP
  command:  docker inspect --format '{''{ .NetworkSettings.Networks.{{ prometheus_docker_network }}.IPAddress}''}' blackbox-exporter
  register: _prometheus_blackboxexporter_container_ip

- name: prometheus | return container IPs
  set_fact:
    prometheus_internal_ip: "{{ _prometheus_container_ip.stdout }}"
    prometheus_blackboxexporter_internal_ip: "{{ _prometheus_blackboxexporter_container_ip.stdout }}"

